apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kube-app-ingress
spec:
  rules:
    - host: kubeapp.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kube-app-service
                port:
                  number: 3000
